# Generated by Django 6.0.2 on 2026-03-09 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('VENDOR', 'صاحب محل (Vendor)'), ('EMPLOYEE', 'موظف (Employee)'), ('CUSTOMER', 'عميل (Customer)')], max_length=10, verbose_name='نوع المستخدم')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف')),
                ('employer', models.ForeignKey(blank=True, limit_choices_to={'role': 'VENDOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='users.userprofile', verbose_name='صاحب العمل (Vendor)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
    ]
