# Generated by Django 6.0.2 on 2026-03-15 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد (Date of Birth)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'ذكر (Male)'), ('FEMALE', 'أنثى (Female)')], max_length=10, null=True, verbose_name='الجنس (Gender)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='employer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'VENDOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile', verbose_name='صاحب العمل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default=0, max_length=15, verbose_name='رقم الهاتف (Phone)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('VENDOR', 'صاحب محل (Vendor)'), ('EMPLOYEE', 'موظف (Employee)'), ('CUSTOMER', 'عميل (Customer)')], default='CUSTOMER', max_length=10, verbose_name='نوع المستخدم'),
        ),
    ]
