# Generated by Django 6.0.2 on 2026-03-15 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
        ('users', '0002_userprofile_date_of_birth_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lists.gender', verbose_name='الجنس (Gender)'),
        ),
    ]
