# Generated by Django 6.0.2 on 2026-03-16 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('slot_type', models.CharField(choices=[('receipt', 'Receipt'), ('delivery', 'Delivery')], max_length=10)),
                ('slots', models.JSONField(default=list)),
                ('is_free', models.BooleanField(default=False)),
                ('unlimit_orders', models.BooleanField(default=False)),
                ('limit_orders', models.PositiveIntegerField(default=0)),
                ('is_close', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day', 'slot_type'],
            },
        ),
    ]
