# Generated by Django 6.0.2 on 2026-03-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_timeslot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['day', 'slot_type', 'slot']},
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='slots',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='slot',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
