# Generated by Django 6.0.2 on 2026-03-18 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_timeslot_options_remove_timeslot_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
