# Generated by Django 6.0.2 on 2026-03-19 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_timeslot_end_timeslot_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='employer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'VENDOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='users.userprofile', verbose_name='صاحب العمل (Employer)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف (Phone)'),
        ),
    ]
