# Generated by Django 6.0.2 on 2026-03-02 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='Name (EN)')),
                ('name_ar', models.CharField(max_length=100, unique=True, verbose_name='الاسم (عربي)')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Service Name (EN)')),
                ('name_ar', models.CharField(max_length=100, verbose_name='اسم الخدمة (عربي)')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Item Name (EN)')),
                ('name_ar', models.CharField(max_length=100, verbose_name='اسم القطعة (عربي)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='Photo / صورة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogue.category')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='ItemServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (EGP)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.item')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.service')),
            ],
            options={
                'verbose_name': 'Price Setting',
                'verbose_name_plural': 'Price Settings',
                'unique_together': {('item', 'service')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='services',
            field=models.ManyToManyField(through='catalogue.ItemServicePrice', to='catalogue.service'),
        ),
    ]
