# Generated by Django 6.0.2 on 2026-03-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemserviceprice',
            options={'verbose_name': 'Price & Percentage Setting', 'verbose_name_plural': 'Price & Percentage Settings'},
        ),
        migrations.AddField(
            model_name='itemserviceprice',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentage (%)'),
        ),
    ]
