# Generated by Django 6.0.2 on 2026-03-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50, verbose_name='النوع (العربية)')),
                ('name_en', models.CharField(max_length=50, verbose_name='Gender (English)')),
            ],
            options={
                'verbose_name': 'نوع',
                'verbose_name_plural': 'قائمة الأنواع (Genders List)',
            },
        ),
    ]
