# Generated by Django 6.0.2 on 2026-03-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='title',
            field=models.CharField(default='Male', max_length=50),
            preserve_default=False,
        ),
    ]
