# Generated by Django 6.0.2 on 2026-03-16 02:53

from django.db import migrations


def populate_cairo_regions(apps, schema_editor):
    Region = apps.get_model('lists', 'Region')
    regions = [
        {"name_en": "Maadi", "name_ar": "المعادي"},
        {"name_en": "Heliopolis", "name_ar": "مصر الجديدة"},  # Fixed key
        {"name_en": "Nasr City", "name_ar": "مدينة نصر"},
        {"name_en": "Zamalek", "name_ar": "الزمالك"},
        {"name_en": "Garden City", "name_ar": "جاردن سيتي"},
        {"name_en": "New Cairo", "name_ar": "القاهرة الجديدة"},
        {"name_en": "Sheikh Zayed", "name_ar": "الشيخ زايد"},
        {"name_en": "6th of October", "name_ar": "السادس من أكتوبر"},
        {"name_en": "Mokattam", "name_ar": "المقطم"},
        {"name_en": "Dokki", "name_ar": "الدقي"},
    ]
    for r in regions:
        # Changed keys here to match the dictionary above
        Region.objects.get_or_create(
            name_en=r["name_en"], name_ar=r["name_ar"])


class Migration(migrations.Migration):

    dependencies = [
        # Ensure this is the migration that creates the table
        ('lists', '0003_region'),
    ]

    operations = [
        # This line is what actually triggers the data insertion
        migrations.RunPython(populate_cairo_regions),
    ]
