# Generated by Django 6.0.2 on 2026-03-17 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20260316_0453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'منطقة', 'verbose_name_plural': 'المناطق (Regions)'},
        ),
    ]
