# Generated by Django 6.0.2 on 2026-03-08 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(editable=False, max_length=20, unique=True, verbose_name='الباركود (Barcode)')),
                ('status', models.CharField(choices=[('RECEIVED', 'استلام من المندوب (Received)'), ('AT_VENDOR', 'في المغسلة (At Vendor)'), ('FINISHED', 'جاهز (Finished)'), ('RETURNED', 'تم التسليم (Returned)')], default='RECEIVED', max_length=20, verbose_name='حالة الطلب (Status)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب (Date)')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات (Orders)',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_code', models.CharField(max_length=50, unique=True, verbose_name='كود القطعة (Tag Code)')),
                ('photo_at_vendor', models.ImageField(blank=True, null=True, upload_to='orders/vendor/', verbose_name='صورة عند المغسلة (Vendor Photo)')),
                ('photo_finished', models.ImageField(blank=True, null=True, upload_to='orders/finished/', verbose_name='صورة بعد الانتهاء (Finished Photo)')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.item', verbose_name='نوع القطعة (Item Type)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='الطلب (Order)')),
            ],
            options={
                'verbose_name': 'قطعة في الطلب',
                'verbose_name_plural': 'قطع الطلبات (Order Items)',
            },
        ),
        migrations.CreateModel(
            name='SelectedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_service_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.itemserviceprice', verbose_name='الخدمة (Service)')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_services', to='orders.orderitem', verbose_name='القطعة')),
            ],
            options={
                'verbose_name': 'خدمة مختارة',
                'verbose_name_plural': 'الخدمات المختارة (Selected Services)',
            },
        ),
    ]
