# Generated by Django 6.0.2 on 2026-03-09 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10, verbose_name='مصاريف التوصيل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار - لم يتم الاستلام بعد (Pending Pickup)'), ('RECEIVED', 'استلام من المندوب (Received)'), ('AT_VENDOR', 'في المغسلة (At Vendor)'), ('FINISHED', 'جاهز (Finished)'), ('RETURNED', 'تم التسليم (Returned)')], default='PENDING', max_length=20, verbose_name='حالة الطلب (Status)'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المجموع الفرعي')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة الضريبة (14%)')),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خدمة التوصيل')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الإجمالي النهائي')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم الدفع')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير (Invoices)',
            },
        ),
    ]
