# Generated by Django 6.0.2 on 2026-03-09 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_fee_alter_order_status_invoice'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'فاتورة', 'verbose_name_plural': '4. الفواتير (Invoices)'},
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CUSTOMER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to='users.userprofile', verbose_name='العميل (Customer)'),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'VENDOR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to='users.userprofile', verbose_name='المحل (Vendor)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مصاريف التوصيل (Delivery Fee)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='رقم الفاتورة (Invoice #)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='تم الدفع؟ (Is Paid?)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار (Issued Date)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order', verbose_name='الطلب (Order)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المجموع الفرعي (Subtotal)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الإجمالي النهائي (Total)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ضريبة القيمة المضافة 14% (VAT)'),
        ),
    ]
