# Generated by Django 6.0.2 on 2026-03-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_invoice_options_order_customer_order_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات (Comment)'),
        ),
    ]
