# Generated by Django 6.0.2 on 2026-03-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_itemserviceprice_options_and_more'),
        ('orders', '0004_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='picked_services',
            field=models.ManyToManyField(blank=True, related_name='orders', to='catalogue.service', verbose_name='الخدمات المختارة للطلب (Picked Services)'),
        ),
    ]
