# Generated by Django 6.0.2 on 2026-03-18 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_customer_latitude_order_customer_longitude_and_more'),
        ('users', '0006_timeslot_end_timeslot_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(null=True, verbose_name='تاريخ الاستلام'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.timeslot', verbose_name='موعد الاستلام'),
        ),
    ]
