# Generated by Django 6.0.2 on 2026-03-18 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_pickup_date_order_time_slot'),
        ('users', '0006_timeslot_end_timeslot_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.timeslot'),
        ),
    ]
