# Generated by Django 6.0.2 on 2026-03-18 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_time_slot'),
        ('users', '0006_timeslot_end_timeslot_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='users.timeslot'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_orders', to='users.timeslot'),
        ),
    ]
