# Generated by Django 6.0.2 on 2026-03-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_delivery_date_alter_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
