# Generated by Django 6.0.2 on 2026-03-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_itemserviceprice_options_and_more'),
        ('orders', '0013_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'طلب', 'verbose_name_plural': 'الطلبات (Orders)'},
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='picked_services',
            field=models.ManyToManyField(blank=True, related_name='orders', to='catalogue.service', verbose_name='الخدمات المختارة (Picked Services)'),
        ),
    ]
